name: Coverage
on:
    push:
        branches:
            - master
            - main
            - staging
    pull_request:
        branches:
            - master
            - main
            - staging

concurrency:
    group: coverage-${{github.ref}}
    cancel-in-progress: true

jobs:
    ecs:
        name: ECS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
              with:
                  php-version: "8.3"
                  tools: composer:v2

            - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1

            - name: Execute ECS
              run: php -d memory_limit=-1 vendor/bin/ecs check src

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
              with:
                  php-version: "8.3"
                  tools: composer:v2

            - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1

            - name: Execute PHPStan
              run: php -d memory_limit=-1 vendor/bin/phpstan analyse src
#  phpunit:
#    name: PHPUnit
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP with PECL extension
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.2'
#          tools: composer:v2
#
#      - uses: ramsey/composer-install@v3
#
#      - name: Execute tests via PHPUnit
#        run: php -d memory_limit=-1 vendor/bin/phpunit
