name: Coverage
on:
    push:
        branches:
            - master
            - main
            - staging
    pull_request:
        branches:
            - master
            - main
            - staging

concurrency:
    group: coverage-${{github.ref}}
    cancel-in-progress: true

jobs:
    ecs:
        name: ECS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: "8.3"
                  tools: composer:v2

            - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1

            - name: Execute ECS
              run: php -d memory_limit=-1 vendor/bin/ecs check src

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: "8.3"
                  tools: composer:v2

            - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1

            - name: Execute PHPStan
              run: php -d memory_limit=-1 vendor/bin/phpstan analyse src
#  phpunit:
#    name: PHPUnit
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP with PECL extension
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.2'
#          tools: composer:v2
#
#      - uses: ramsey/composer-install@v3
#
#      - name: Execute tests via PHPUnit
#        run: php -d memory_limit=-1 vendor/bin/phpunit
